# Generated by Django 5.1.3 on 2025-01-29 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('address', models.URLField()),
            ],
            options={
                'db_table': 'body',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='body.body')),
            ],
            options={
                'db_table': 'floors',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.body')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.floor')),
            ],
            options={
                'db_table': 'offices',
            },
        ),
        migrations.CreateModel(
            name='PackageDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_devices', to='body.office')),
            ],
            options={
                'db_table': 'package_device',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='type_devices.typedevice')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='body.packagedevice')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='body.status')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='body.device')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='body.office')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='body.status')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
