# Generated by Django 5.1.3 on 2025-01-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='body',
        ),
        migrations.AlterField(
            model_name='body',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
