# Generated by Django 5.1.3 on 2024-11-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typedevice',
            table='type_devices',
        ),
    ]
